# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish BeeEeeLibs.HttpServerBase
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/HttpServerBase/HttpServerBase/HttpServerBase.csproj"
        NUGET_KEY: $${{secrets.NUGET_API_KEY}}
    - name: Show Environment
      run: ls -l
    - name: Publish BeeEeeLibs.MySql
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: MySql/MySql.csproj
        NUGET_KEY: $${{secrets.NUGET_API_KEY}}
    
